const products = [
  {
    id: 1,
    category: "toy",
    emoji: "🐶",
    image: "./src/img/shop1.jpeg",
    name: "Interactive Treat Dispensing Toy",
    stars: "⭐⭐⭐⭐",
    description:
      "This toy not only keeps your pet active and entertained, but it also strengthens the bond between you and your pet, creating moments of fun and connection. This Interactive Treat Dispensing Toy for Pets in the shape of a flying saucer is a perfect tool to keep your pet active and entertained. This toy not only provides fun, but it also stimulates your pet's mind by challenging them to chase and catch the flying saucer while getting treats or food. With its durable and sturdy design, this toy is ideal for dogs and cats of all ages and sizes, promoting physical and mental exercise for a healthier and happier life.",
    price: 12.99,
  },
  {
    id: 2,
    category: "food",
    emoji: "🐱",
    image: "./src/img/shop2.webp",
    name: "Go! Sensitivities limited ingredient grain free duck recipe for cats x 3.7 kg",
    stars: "⭐⭐⭐⭐⭐",
    description: "This GO! SENSITIVITIES recipe for all stages is ideal for cats with special nutritional needs such as food allergies and sensitive stomachs. It contains premium duck as its only source of protein and is free of grains, gluten, potato, wheat, corn or soy.",
    price: 25.5,
  },
  {
    id: 3,
    category: "medicine",
    emoji: "🐶",
    image: "./src/img/shop3.webp",
    name: "Orenda dermatological x 100 gr",
    stars: "⭐⭐⭐",
    description: "Antiseptic, repellent and healing cream, with natural extracts.",
    price: 15.75,
  },
  {
    id: 4,
    category: "clothes",
    emoji: "🐱",
    image: "./src/img/shop4.webp",
    name: "Cat Clothes, Warm Sweater",
    stars: "⭐⭐⭐⭐",
    description: "Delicate cat sweater, soft, warm and easy to put on, ideal for cold days.",
    price: 18.0,
  },
  {
    id: 5,
    category: "toy",
    emoji: "🐶",
    image: "./src/img/shop5.webp",
    name: "Balls and Rope Throws Exercise Antitartar Blue Color",
    stars: "⭐⭐⭐⭐",
    description: "Attention dog lovers! The Dog Toy with 2 Balls and Knotted Rope is your furry friend's favorite. Perfect for medium and large breeds, this interactive toy is not just a fun object, it's an all-in-one. Its colorful and knotted design will instantly capture your dog's attention, stimulating physical and mental activity. Throw the ball and let the fun begin! Its special texture helps clean teeth and fight tartar, the durable material strengthens jaws during play and it's made of material that you can easily wash.",
    price: 9.99,
  },
  {
    id: 6,
    category: "food",
    emoji: "🐶",
    image: "./src/img/shop6.webp",
    name: "PEDIGREE Grilled Beef & Veggies Adult Dry Dog Food, 18 lb Bag",
    stars: "⭐⭐⭐⭐⭐",
    description: " Ground Whole Grain Corn, Meat and Bone Meal, Soybean Meal, Animal Fat (Source of Omega 6 Fatty Acids [Preserved with BHA & Citric Acid]), Corn Gluten Meal, Natural Flavor, Dried Plain Beet Pulp, Chicken Byproduct Meal, Salt, Ground Whole Grain Wheat, Brewers Rice, Potassium Chloride, Calcium Carbonate, Choline Chloride, Dried Peas, DL-Methionine, Natural Grilled Steak Flavor, Zinc Sulfate, Yellow 6, Monocalcium Phosphate, Vitamin E Supplement, L-Tryptophan, Yellow 5, Red 40, Blue 2, Dried Carrots, Niacin Supplement (Vitamin B3), Copper Sulfate, Sodium Selenite, Potassium Iodide, D-Calcium Pantothenate (Source of Vitamin B5), Vitamin A Supplement, Riboflavin Supplement (Vitamin B2), Vitamin B12 Supplement, Thiamine Mononitrate (Vitamin B1), Vitamin D3 Supplement, Pyridoxine Hydrochloride (Vitamin B6), Folic Acid.",
    price: 30.99,
  },
  {
    id: 7,
    category: "medicine",
    emoji: "🐱",
    image: "./src/img/shop7.webp",
    name: "Total Antiparasitic FLC Cats - Blister",
    stars: "⭐⭐⭐⭐",
    description: "Total FLC is a broad-spectrum internal antiparasitic for cats that is formulated for the control and treatment of cestodes, nematodes and giardia that can affect our dogs. Contains 1 blister with 2 tablets.",
    price: 8.5,
  },
  {
    id: 8,
    category: "clothes",
    emoji: "🐶",
    image: "./src/img/shop8.webp",
    name: "Orange Pet Hooded Bag – Ref. 1000",
    stars: "⭐⭐⭐",
    description: "Keep your pet warm and stylish with our hooded pet coat. Made from high-quality materials and designed with a leash opening, it's perfect for any occasion. Order now and keep your furry companion warm on cold days!",
    price: 22.3,
  },
  {
    id: 9,
    category: "toy",
    emoji: "🐱",
    image: "./src/img/shop9.avif",
    name: "Laser pointer for cats",
    stars: "⭐⭐⭐⭐⭐",
    description: "White cat paw shaped laser 5 different laser designs in one heart, bone, paw print, fish, mouse. Red laser color USB rechargeable It is an excellent toy to entertain your pet. Remember to avoid your pet's frustration by sharing a delicious snack after or during the game with the laser.",
    price: 7.99,
  },
  {
    id: 10,
    category: "food",
    emoji: "🐶",
    image: "./src/img/shop10.webp",
    name: "Smartbones Dog Treats Chicken Bones 16pcs",
    stars: "⭐⭐⭐⭐⭐",
    description: "Your dog won't be able to resist the exquisite flavour of Smartbones Chicken Mini premium snacks. They are made with vegetables and have an inner layer of chicken that will brighten up your canine friend's days.",
    price: 12.0,
  },
  {
    id: 11,
    category: "medicine",
    emoji: "🐶",
    image: "./src/img/shop11.jpg",
    name: "NexGard Flea Control for Dogs from 2 to 4 Kg",
    stars: "⭐⭐⭐⭐",
    description: "Supplements to promoteNexGard® is a new dimension in protection for your pets and the most complete prescription designed for effective control and prevention against fleas and ticks, preferred by pets over other products, thanks to its irresistible beef flavor.",
    price: 20.99,
  },
  {
    id: 12,
    category: "clothes",
    emoji: "🐱",
    image: "./src/img/shop12.webp",
    name: "Bonaweite Sphynx - Cat Clothes, Cat Sweaters",
    stars: "⭐⭐⭐",
    description: "Sphynx cat clothes are made of breathable and soft cotton, skin-friendly, comfortable for daily wear.",
    price: 15.25,
  },
  {
    id: 13,
    category: "toy",
    emoji: "🐶",
    image: "./src/img/shop13.webp",
    name: "Flying Boomerang Sound Frisbee Dog Toy",
    stars: "⭐⭐⭐⭐",
    description: "Boomerang style pet frisbee, durable, rubber for your pet to play with all day long.",
    price: 5.99,
  },
  {
    id: 14,
    category: "food",
    emoji: "🐱",
    image: "./src/img/shop14.webp",
    name: "Churu Assorted Seafood 20 Tubes",
    stars: "⭐⭐⭐⭐",
    description: "Discover the irresistible Churu Seafood Variety, a feast of ocean flavors specially designed to delight your feline. This pack of 20 tubes comes with a gourmet selection that includes 5 tubes with the rich flavor of salmon, 5 tubes with shrimp for an intense flavor experience, 5 tubes with a seafood flavor that evokes the freshness of the sea, and 5 tubes with bonito flakes, a delight that will make your cat purr with pleasure. Presented by Inaba, a trusted brand in feline nutrition, the CHURU line is synonymous with quality and satisfaction. This Seafood assortment is the perfect gift for cats of any age, providing not only a moment of joy but also a way to enrich their diet with flavors they love.",
    price: 16.5,
  },
  {
    id: 15,
    category: "medicine",
    emoji: "🐶",
    image: "./src/img/shop15.webp",
    name: "Combo Omegas 3,6 and 9 + Multivitamin Mungos Dogs",
    stars: "⭐⭐⭐⭐⭐",
    description: "Niacinamide – vit b3 175 mg pantothenic acid vit b5 248 mg pyridoxine vit b6 93 mg riboflavin vit b2 37 mg thiamine vit b1 26 mg retinol vit a 7000 mcg cyanocobalamin vit b12 1300 mcg dl alphatocopherol vit e 8.8 iu/g ascorbic acid vit c 1000 mg vitamin.",
    price: 13.99,
  },
];

export default products;
